<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Versover'))->setSeparator(' &bull; ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ; ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/dist/css/style.min.css')
            ->prependStylesheet($this->basePath() . '/vendor/bootstrap-material-design/dist/css/material-wfont.min.css')
            ->prependStylesheet($this->basePath() . '/vendor/bootstrap-material-design/dist/css/material.min.css')
            ->prependStylesheet($this->basePath() . '/vendor/bootstrap-material-design/dist/css/ripples.min.css')
            ->prependStylesheet($this->basePath() . 'http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
            ->prependStylesheet($this->basePath() . '/vendor/bootstrap/dist/css/bootstrap.min.css')
        ; ?>

    </head>
    <body>
        <div class="container">
            <!-- main nav -->
            <div class="navbar navbar-default">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <h1 id="brand"><a class="navbar-brand" href="/">Versover</a></h1>
                </div>
                <div class="navbar-collapse collapse navbar-responsive-collapse">
                    <?php echo $this->navigation('navigation')->menu()->setULClass('nav navbar-nav navbar-right'); ?>
                </div>
            </div><!-- /main nav -->

            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <footer id="footer" class="text-center">
            <p>&copy; Versover <?php echo date('Y'); ?></p>
        </footer>
        <div class="domain-names hidden-xs"></div>
        <?php
        $script =  $this->inlineScript();
        $script
            ->appendFile($this->basePath() . '/vendor/jquery/dist/jquery.min.js')
            ->appendFile($this->basePath() . '/vendor/bootstrap/dist/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/vendor/bootstrap-material-design/dist/js/ripples.min.js')
            ->appendFile($this->basePath() . '/vendor/bootstrap-material-design/dist/js/material.min.js')
            ->appendFile($this->basePath() . '/dist/js/script.min.js');

        echo $script;
        ?>
    </body>
</html>