<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Versover'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ; ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/dist/css/style.min.css')
            ->prependStylesheet($this->basePath() . '/vendor/bootstrap-material-design/dist/css/material.min.css')
            ->prependStylesheet($this->basePath() . '/vendor/bootstrap/dist/css/bootstrap.min.css')
        ; ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
            <footer>
                <p>&copy; Versover <?php echo date('Y'); ?></p>
            </footer>
        </div> <!-- /container -->
        <?php
        $script =  $this->inlineScript();
        $script
            ->appendFile($this->basePath() . '/vendor/jquery/dist/jquery.min.js')
            ->appendFile($this->basePath() . '/vendor/bootstrap/dist/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/vendor/bootstrap-material-design/dist/js/material.min.js')
            ->appendFile($this->basePath() . '/dist/js/script.min.js');

        echo $script;
        ?>
    </body>
</html>