<?php
$title = 'Home';
$this->headTitle($title);
?>
<div class="row">
    <div class="col col-xs-10 col-xs-offset-1">
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title web-development">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Website development
                        </a>
                    </h4>

                    <i class="mdi-content-add"></i>
                </div>
                <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingTwo">
                    <h4 class="panel-title e-commerce">
                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            E-commerce
                        </a>
                    </h4>

                    <i class="mdi-content-add"></i>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                    <div class="panel-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingThree">
                    <h4 class="panel-title file-maker">
                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            FileMaker
                        </a>
                    </h4>

                    <i class="mdi-content-add"></i>
                </div>
                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                    <div class="panel-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingFour">
                    <h4 class="panel-title design">
                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseThree">
                            Design
                        </a>
                    </h4>

                    <i class="mdi-content-add"></i>
                </div>
                <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
                    <div class="panel-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                    </div>
                </div>
            </div>

            <div class="paint-bucket hidden-sm hidden-xs"></div>

        </div>

        <div class="carousel slide hidden-xs" data-ride="carousel" id="quote-carousel">
            <!-- Carousel Slides / Quotes -->
            <div class="carousel-inner">

                <!-- Quote 1 -->
                <div class="item active">
                    <blockquote>
                        <div class="row">
                            <div class="quote center-block">
                                <p><i class="mdi-editor-format-quote"></i> <?php echo $this->translate('Measuring software productivity by lines of code is like measuring progress on an airplane by how much it weighs.'); ?></p>
                                <small>Bill Gates</small>
                            </div>
                        </div>
                    </blockquote>
                </div>
                <!-- Quote 2 -->
                <div class="item">
                    <blockquote>
                        <div class="row">
                            <div class="quote center-block">
                                <p><i class="mdi-editor-format-quote"></i> <?php echo $this->translate('To Iterate is Human, to Recurse, Divine.'); ?></p>
                                <small>Peter Deutsch</small>
                            </div>
                        </div>
                    </blockquote>
                </div>
                <!-- Quote 3 -->
                <div class="item">
                    <blockquote>
                        <div class="row">
                            <div class="quote center-block">
                                <p><i class="mdi-editor-format-quote"></i> <?php echo $this->translate('Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.'); ?></p>
                                <small>Martin Golding</small>
                            </div>
                        </div>
                    </blockquote>
                </div>
                <!-- Quote 4 -->
                <div class="item">
                    <blockquote>
                        <div class="row">
                            <div class="quote center-block">
                                <p><i class="mdi-editor-format-quote"></i> <?php echo $this->translate('I conclude that there are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is make it so complicated that there are no obvious deficiencies.'); ?></p>
                                <small>R. Hoare</small>
                            </div>
                        </div>
                    </blockquote>
                </div>
                <!-- Quote 5 -->
                <div class="item">
                    <blockquote>
                        <div class="row">
                            <div class="quote center-block">
                                <p><i class="mdi-editor-format-quote"></i> <?php echo $this->translate('Every program has two purposes: The one for which it was written and another for which it wasn’t.'); ?></p>
                                <small>Alan Jay Perlis</small>
                            </div>
                        </div>
                    </blockquote>
                </div>
            </div>
            <!-- Carousel Buttons Next/Prev -->
            <a data-slide="prev" href="#quote-carousel" class="left carousel-control"><i class="mdi-navigation-chevron-left"></i></a>
            <a data-slide="next" href="#quote-carousel" class="right carousel-control"><i class="mdi-navigation-chevron-right"></i></a>
        </div>
    </div>
</div>
<div class="row bottom">
    <div class="col col-md-4">
        <h3>About</h3>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex fugiat nisi repellendus sint tenetur.
            Accusantium ad, architecto, blanditiis consequatur debitis eos exercitationem iusto possimus qui quidem rem
            repellat repellendus sit.
        </p>
    </div>
    <div class="col col-md-4">
        <h3>Inquiries</h3>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda, autem culpa dolore doloremque doloribus
            eaque in iste magnam maxime mollitia nostrum omnis, porro quod quos ratione rerum sit sunt velit.
        </p>
    </div>
    <div class="col col-md-4">
        <h3>Contacts</h3>

        <ul class="list-unstyled">
            <li><h4><i class="fa fa-phone fa-2x"></i> Phone: +38(067)562-37-77</h4></li>
            <li><h4><i class="fa fa-envelope-o fa-2x"></i> Email: <a href="mailto:versoverteam@gmail.com">versoverteam@gmail.com</a></h4></li>
            <li><h4><i class="fa fa-skype fa-2x"></i> Skype: <a href="skype:versover?chat">versover</a></h4></li>
        </ul>
    </div>
</div>